In [19]:
import pandas as pd
import psutil, os

def memory_usage_mb():
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024**2

In [ ]:
df = pd.read_csv('../data/customers-100000.csv')

In [8]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,ffeCAb7AbcB0f07,Jared,Jarvis,Sanchez-Fletcher,Hatfieldshire,Eritrea,274.188.8773x41185,001-215-760-4642x969,gabriellehartman@benjamin.com,2021-11-11,https://www.mccarthy.info/
1,2,b687FfC4F1600eC,Marie,Malone,Mckay PLC,Robertsonburgh,Botswana,283-236-9529,(189)129-8356x63741,kstafford@sexton.com,2021-05-14,http://www.reynolds.com/
2,3,9FF9ACbc69dcF9c,Elijah,Barrera,Marks and Sons,Kimbury,Barbados,8252703789,459-916-7241x0909,jeanettecross@brown.com,2021-03-17,https://neal.com/
3,4,b49edDB1295FF6E,Sheryl,Montgomery,"Kirby, Vaughn and Sanders",Briannaview,Antarctica (the territory South of 60 deg S),425.475.3586,(392)819-9063,thomassierra@barrett.com,2020-09-23,https://www.powell-bryan.com/
4,5,3dcCbFEB17CCf2E,Jeremy,Houston,Lester-Manning,South Brianna,Micronesia,+1-223-666-5313x4530,252-488-3850x692,rubenwatkins@jacobs-wallace.info,2020-09-18,https://www.carrillo.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,67F24BEBAa16d1c,Dana,Winters,"Pham, Conner and Wade",Kirkfurt,Sierra Leone,820-930-7616,+1-061-779-5511x3267,ppittman@watson.com,2020-05-30,https://www.maynard.com/
99996,99997,17b1dbDaB2ad0fB,Gabriela,Pacheco,Fletcher-Hodge,Virginiahaven,Comoros,+1-480-464-8646,(015)822-1443x33211,murillojeremiah@mcmahon-medina.com,2022-04-09,http://www.eaton.com/
99997,99998,c586CFBA6fb9dcC,Mikayla,Hubbard,Austin Ltd,Sheriville,Mayotte,+1-567-149-3941x67118,361-900-3348,orhodes@harding-galloway.biz,2022-03-05,https://hayes.com/
99998,99999,bb6cb6AC9d0CAf7,Javier,Berg,Welch Inc,Stephenschester,Belarus,(381)105-4698,360-905-2308x301,rodneytanner@jennings-boone.net,2021-12-29,http://zuniga.com/
99999,100000,FaE5E3c1Ea0dEc2,Kaylee,Hubbard,Booker-Luna,New Karina,Estonia,(184)132-6303x4566,157.189.4485,krystal67@sweeney-clements.com,2020-07-11,https://www.walter.com/

In [15]:
print(f"Countries represented: {df['Country'].nunique()}")
print(f"Most common country: {df['Country'].value_counts().idxmax()} with {df['Country'].value_counts().max()} customers")
print(f"Most common company: {df['Company'].value_counts().idxmax()} with {df['Company'].value_counts().max()} customers")
print(f"Earliest subscription: {df['Subscription Date'].min()} from {df['Country'].value_counts().idxmin()}")
print(f"Latest subscription: {df['Subscription Date'].max()} from {df['Country'].value_counts().idxmax()}")

Countries represented: 243
Most common country: Congo with 835 customers
Most common company: Wilkerson Ltd with 17 customers
Earliest subscription: 2020-01-01 from Greece
Latest subscription: 2022-05-29 from Congo

## 2. Please parse large CSV, customers-2000000.csv and keep the memory low.

### Manual Way (Chunking using Pandas)

In [18]:
chunksize = 50000  # process 50k rows at a time
unique_companies_with_count = {}
unique_countries_with_count = {}
customer_count = 0
earliest_subscription = None
latest_subscription = None

for chunk in pd.read_csv("../data/customers-2000000.csv", chunksize=chunksize):
    for country in chunk["Country"].unique():
        unique_countries_with_count[country] = unique_countries_with_count.get(country, 0) + 1
    for company in chunk["Company"].unique():
        unique_companies_with_count[company] = unique_companies_with_count.get(company, 0) + 1
    earliest_subscription = min(earliest_subscription, chunk["Subscription Date"].min()) if earliest_subscription is not None else chunk["Subscription Date"].min()
    latest_subscription = max(latest_subscription, chunk["Subscription Date"].max()) if latest_subscription is not None else chunk["Subscription Date"].max()

    customer_count += chunk.shape[0]

print(f"Countries represented: {len(unique_countries_with_count)}")
print(f"Most common country: {max(unique_countries_with_count, key=unique_countries_with_count.get)} with {unique_countries_with_count[max(unique_countries_with_count, key=unique_countries_with_count.get)]} customers")
print(f"Most common company: {max(unique_companies_with_count, key=unique_companies_with_count.get)} with {unique_companies_with_count[max(unique_companies_with_count, key=unique_companies_with_count.get)]} customers")
print(f"Earliest subscription: {earliest_subscription} from {min(unique_countries_with_count, key=unique_countries_with_count.get)}")
print(f"Latest subscription: {latest_subscription} from {max(unique_countries_with_count, key=unique_countries_with_count.get)}")

Countries represented: 243
Most common country: British Indian Ocean Territory (Chagos Archipelago) with 40 customers
Most common company: Ochoa PLC with 40 customers
Earliest subscription: 2020-01-01 from British Indian Ocean Territory (Chagos Archipelago)
Latest subscription: 2022-05-30 from British Indian Ocean Territory (Chagos Archipelago)

## 3. Explain how it's different from splitting the small vs large files.

Small files:

- Can fit into memory (RAM).

- Faster since everything is in memory.

- Can use the pandas aggregation function directly for insight

Large files:

- Possibly exceed memory limits.

- Better to use streaming or chunking instead of fitting the whole data in memory.

- Trade-off: slower, but scalable.

- Requires designing aggregations function specifically that donâ€™t require holding everything at once (e.g., counts, averages, incremental updates).

## 4. Deploy the vector DB on your own, and implement the `vector cosine similarity` without using a high level library.

In [ ]:
import numpy as np

class VectorDB:
    def __init__(self):
        self.vectors = {}
    
    def add(self, key, vector):
        self.vectors[key] = np.array(vector, dtype=np.float32)
    
    def search(self, query_vector, top_k=5):
        query_vector = np.array(query_vector, dtype=np.float32)
        scores = []
        for key, vector in self.vectors.items():
            score = self.cosine_similarity(query_vector, vector)
            scores.append((key, score))
        return sorted(scores, key=lambda x: x[1], reverse=True)[:top_k]
    
    def cosine_similarity(self, a, b):
        dot = np.dot(a, b)
        norm_a = np.linalg.norm(a)
        norm_b = np.linalg.norm(b)
        return dot / (norm_a * norm_b)